services:
  mariadb:
    image: mariadb:10.11.4-jammy
    container_name: ${PROJECT_NAME}_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      --max_connections=25
      --innodb_buffer_pool_size=64M
      --innodb_log_buffer_size=8M
      --key_buffer_size=8M
      --performance_schema=OFF
      --skip-name-resolve
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  php-fpm:
    build: ./php
    container_name: ${PROJECT_NAME}_phpfpm
    restart: always
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-mariadb}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  flask:
    build: ./python
    container_name: ${PROJECT_NAME}_flask
    restart: always
    expose:
      - "${FLASK_PORT}"
    volumes:
      - ./python:/app
    depends_on:
      - mariadb
    environment:
      DB_HOST: ${FLASK_DB_HOST}
      DB_USER: ${FLASK_DB_USER}
      DB_PASS: ${FLASK_DB_PASS}
      DB_NAME: ${FLASK_DB_NAME}
      PORT: ${FLASK_PORT}
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - flask
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${PHPMYADMIN_HOST}
      PMA_USER: ${PHPMYADMIN_USER}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
